/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parqueadero;

/**
 *
 * @author andre
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        Ingreso6 = new javax.swing.JButton();
        Ver_Tabla6 = new javax.swing.JButton();
        V_4_R6 = new javax.swing.JButton();
        V_2_R6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Eliminar6 = new javax.swing.JButton();
        Salir6 = new javax.swing.JButton();
        Tipo_V6 = new javax.swing.JComboBox<>();
        Placa6 = new javax.swing.JTextField();
        Placa_Label6 = new javax.swing.JLabel();
        Tipo_v_Label6 = new javax.swing.JLabel();
        num_vehiculo_label6 = new javax.swing.JLabel();
        Registrar6 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        Tabla6 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        Ingreso6.setBackground(new java.awt.Color(102, 0, 0));
        Ingreso6.setFont(new java.awt.Font("SWIsop2", 0, 15)); // NOI18N
        Ingreso6.setForeground(new java.awt.Color(255, 255, 255));
        Ingreso6.setText("Ingreso Vehículo");
        Ingreso6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingreso6ActionPerformed(evt);
            }
        });

        Ver_Tabla6.setBackground(new java.awt.Color(102, 0, 0));
        Ver_Tabla6.setFont(new java.awt.Font("SWIsop2", 0, 15)); // NOI18N
        Ver_Tabla6.setForeground(new java.awt.Color(255, 255, 255));
        Ver_Tabla6.setText("Visualizar Tabla");
        Ver_Tabla6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_Tabla6ActionPerformed(evt);
            }
        });

        V_4_R6.setBackground(new java.awt.Color(102, 0, 0));
        V_4_R6.setFont(new java.awt.Font("SWIsop2", 0, 15)); // NOI18N
        V_4_R6.setForeground(new java.awt.Color(255, 255, 255));
        V_4_R6.setText("Vehículos 4 Ruedas");
        V_4_R6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_4_R6ActionPerformed(evt);
            }
        });

        V_2_R6.setBackground(new java.awt.Color(102, 0, 0));
        V_2_R6.setFont(new java.awt.Font("SWIsop2", 0, 15)); // NOI18N
        V_2_R6.setForeground(new java.awt.Color(255, 255, 255));
        V_2_R6.setText("Vehículos 2 Ruedas");
        V_2_R6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_2_R6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 0, 0));
        jButton7.setFont(new java.awt.Font("SWIsop2", 0, 15)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Total Vehículos/Pagar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        Eliminar6.setBackground(new java.awt.Color(102, 0, 0));
        Eliminar6.setFont(new java.awt.Font("SWIsop2", 0, 15)); // NOI18N
        Eliminar6.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar6.setText("Eliminar Vehículo");
        Eliminar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar6ActionPerformed(evt);
            }
        });

        Salir6.setBackground(new java.awt.Color(102, 0, 0));
        Salir6.setFont(new java.awt.Font("SWIsop2", 0, 15)); // NOI18N
        Salir6.setForeground(new java.awt.Color(255, 255, 255));
        Salir6.setText("Salir");
        Salir6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir6ActionPerformed(evt);
            }
        });

        Tipo_V6.setBackground(new java.awt.Color(204, 204, 204));
        Tipo_V6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto", "Bicicleta y Ciclomotores" }));

        Placa6.setBackground(new java.awt.Color(153, 153, 153));
        Placa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Placa6ActionPerformed(evt);
            }
        });

        Placa_Label6.setText("Placa");

        Tipo_v_Label6.setForeground(new java.awt.Color(255, 255, 255));
        Tipo_v_Label6.setText("Tipo de Vehículo");

        num_vehiculo_label6.setForeground(new java.awt.Color(255, 255, 255));
        num_vehiculo_label6.setText("# Vehículo: 1");

        Registrar6.setBackground(new java.awt.Color(102, 0, 0));
        Registrar6.setForeground(new java.awt.Color(255, 255, 255));
        Registrar6.setText("Registrar");
        Registrar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar6ActionPerformed(evt);
            }
        });

        Tabla6.setBackground(new java.awt.Color(149, 90, 90));
        Tabla6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(Tabla6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Placa_Label6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_vehiculo_label6)
                        .addGap(146, 146, 146)
                        .addComponent(Tipo_v_Label6))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Placa6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Tipo_V6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Ver_Tabla6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Eliminar6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ingreso6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(V_2_R6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(V_4_R6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Registrar6)
                            .addComponent(Salir6))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Placa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tipo_V6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Placa_Label6)
                            .addComponent(num_vehiculo_label6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tipo_v_Label6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingreso6)
                    .addComponent(V_2_R6)
                    .addComponent(Registrar6))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Eliminar6)
                            .addComponent(V_4_R6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ver_Tabla6)
                            .addComponent(jButton7)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Salir6)))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingreso6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso6ActionPerformed
        Placa.setVisible(true);
        Tipo_V.setVisible(true);
        Registrar.setVisible(true);
        num_vehiculo_label.setVisible(true);
        Registrar.setText("Registrar");
        Auxiliar.setVisible(false);
    }//GEN-LAST:event_Ingreso6ActionPerformed

    private void Ver_Tabla6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_Tabla6ActionPerformed
        Fill_Rows(0);
        Tabla.setModel(modelo);
        Auxiliar.setVisible(false);
    }//GEN-LAST:event_Ver_Tabla6ActionPerformed

    private void V_4_R6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_4_R6ActionPerformed
        Fill_Rows(4);
        Tabla.setModel(modelo);
        Auxiliar.setVisible(false);
    }//GEN-LAST:event_V_4_R6ActionPerformed

    private void V_2_R6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_2_R6ActionPerformed
        Tabla.setModel(modelo);
        Auxiliar.setVisible(false);
        Fill_Rows(2);
    }//GEN-LAST:event_V_2_R6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int total_pagos = 0;
        for(int c = 0; c < lista.size(); c++){
            total_pagos += (lista.get(c).Minutos_Pagar() * valor$(lista.get(c).getTipo_v()));
        }
        Auxiliar.setText("Numero de vehÃ­culos: " +  lista.size() + "   Total pagos: $" + total_pagos );
        Auxiliar.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Eliminar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar6ActionPerformed
        Placa_Label.setVisible(true);
        Placa.setVisible(true);
        Registrar.setText("Eliminar");
        Registrar.setVisible(true);
        Auxiliar.setVisible(false);
    }//GEN-LAST:event_Eliminar6ActionPerformed

    private void Salir6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Salir6ActionPerformed

    private void Placa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Placa6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Placa6ActionPerformed

    private void Registrar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar6ActionPerformed
        if("Registrar".equals(Registrar.getText())){
            num_vehiculo++;
            vehiculo[num_vehiculo-1] = new Vehiculo(tiempo.getHour(),tiempo.getMinute(),Placa.getText(),Tipo_V.getSelectedItem().toString(),num_vehiculo);
            num_vehiculo_label.setText("# VehÃ­culo: " + num_vehiculo);
            Tipo_V.setVisible(false);
            num_vehiculo_label.setVisible(false);
            lista.add(vehiculo[num_vehiculo-1]);
        }else{
            for(int c = 0; c < lista.size(); c++){
                if(lista.get(c).getPlaca().equals(Placa.getText()))
                lista.remove(c);
            }
        }
        Registrar.setVisible(false);
        Placa.setVisible(false);
        Placa_Label.setVisible(false);
        Placa.setText("");
    }//GEN-LAST:event_Registrar6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Auxiliar;
    private javax.swing.JLabel Auxiliar1;
    private javax.swing.JLabel Auxiliar2;
    private javax.swing.JLabel Auxiliar3;
    private javax.swing.JLabel Auxiliar4;
    private javax.swing.JLabel Auxiliar5;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JButton Eliminar2;
    private javax.swing.JButton Eliminar3;
    private javax.swing.JButton Eliminar4;
    private javax.swing.JButton Eliminar5;
    private javax.swing.JButton Eliminar6;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Hora1;
    private javax.swing.JLabel Hora2;
    private javax.swing.JLabel Hora3;
    private javax.swing.JLabel Hora4;
    private javax.swing.JLabel Hora5;
    private javax.swing.JButton Ingreso;
    private javax.swing.JButton Ingreso1;
    private javax.swing.JButton Ingreso2;
    private javax.swing.JButton Ingreso3;
    private javax.swing.JButton Ingreso4;
    private javax.swing.JButton Ingreso5;
    private javax.swing.JButton Ingreso6;
    private javax.swing.JTextField Placa;
    private javax.swing.JTextField Placa1;
    private javax.swing.JTextField Placa2;
    private javax.swing.JTextField Placa3;
    private javax.swing.JTextField Placa4;
    private javax.swing.JTextField Placa5;
    private javax.swing.JTextField Placa6;
    private javax.swing.JLabel Placa_Label;
    private javax.swing.JLabel Placa_Label1;
    private javax.swing.JLabel Placa_Label2;
    private javax.swing.JLabel Placa_Label3;
    private javax.swing.JLabel Placa_Label4;
    private javax.swing.JLabel Placa_Label5;
    private javax.swing.JLabel Placa_Label6;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Registrar1;
    private javax.swing.JButton Registrar2;
    private javax.swing.JButton Registrar3;
    private javax.swing.JButton Registrar4;
    private javax.swing.JButton Registrar5;
    private javax.swing.JButton Registrar6;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Salir1;
    private javax.swing.JButton Salir2;
    private javax.swing.JButton Salir3;
    private javax.swing.JButton Salir4;
    private javax.swing.JButton Salir5;
    private javax.swing.JButton Salir6;
    private javax.swing.JTable Tabla;
    private javax.swing.JTable Tabla1;
    private javax.swing.JTable Tabla2;
    private javax.swing.JTable Tabla3;
    private javax.swing.JTable Tabla4;
    private javax.swing.JTable Tabla5;
    private javax.swing.JTable Tabla6;
    private javax.swing.JComboBox<String> Tipo_V;
    private javax.swing.JComboBox<String> Tipo_V1;
    private javax.swing.JComboBox<String> Tipo_V2;
    private javax.swing.JComboBox<String> Tipo_V3;
    private javax.swing.JComboBox<String> Tipo_V4;
    private javax.swing.JComboBox<String> Tipo_V5;
    private javax.swing.JComboBox<String> Tipo_V6;
    private javax.swing.JLabel Tipo_v_Label;
    private javax.swing.JLabel Tipo_v_Label1;
    private javax.swing.JLabel Tipo_v_Label2;
    private javax.swing.JLabel Tipo_v_Label3;
    private javax.swing.JLabel Tipo_v_Label4;
    private javax.swing.JLabel Tipo_v_Label5;
    private javax.swing.JLabel Tipo_v_Label6;
    private javax.swing.JButton V_2_R;
    private javax.swing.JButton V_2_R1;
    private javax.swing.JButton V_2_R2;
    private javax.swing.JButton V_2_R3;
    private javax.swing.JButton V_2_R4;
    private javax.swing.JButton V_2_R5;
    private javax.swing.JButton V_2_R6;
    private javax.swing.JButton V_4_R;
    private javax.swing.JButton V_4_R1;
    private javax.swing.JButton V_4_R2;
    private javax.swing.JButton V_4_R3;
    private javax.swing.JButton V_4_R4;
    private javax.swing.JButton V_4_R5;
    private javax.swing.JButton V_4_R6;
    private javax.swing.JButton Ver_Tabla;
    private javax.swing.JButton Ver_Tabla1;
    private javax.swing.JButton Ver_Tabla2;
    private javax.swing.JButton Ver_Tabla3;
    private javax.swing.JButton Ver_Tabla4;
    private javax.swing.JButton Ver_Tabla5;
    private javax.swing.JButton Ver_Tabla6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel num_vehiculo_label;
    private javax.swing.JLabel num_vehiculo_label1;
    private javax.swing.JLabel num_vehiculo_label2;
    private javax.swing.JLabel num_vehiculo_label3;
    private javax.swing.JLabel num_vehiculo_label4;
    private javax.swing.JLabel num_vehiculo_label5;
    private javax.swing.JLabel num_vehiculo_label6;
    // End of variables declaration//GEN-END:variables
}
